BUILD-1287 Add .github/CODEOWNERS
SonarSource/release-notes-generator pull request #3
Opened 2022-03-18 08:40 UTC by Godin

2022-03-18 08:43 UTC, costin-zaharia-sonarsource commented on .github/CODEOWNERS
> +.github/CODEOWNERS @SonarSource/languages-team-dotnet
If I remember correctly this tool is used by the sonar lint team too. @duncanp-sonar would you like to be added as an owner too?

2022-03-23 13:34 UTC, costin-zaharia-sonarsource requested changes
Could you please add @duncanp-sonar and @rita-sonarsource too?

2022-03-24 20:34 UTC, Godin commented
@costin-zaharia-sonarsource done

2022-03-25 08:09 UTC, costin-zaharia-sonarsource approved these changes
LGMT!

2022-03-25 08:09 UTC, merged